pot_deposit:
  target:
    entity:
      integration: monzo
      domain: sensor
  fields:
    amount_in_minor_units:
      required: true
      selector:
        number:
          min: 0
          max: 200000
pot_withdraw:
  target:
    entity:
      integration: monzo
      domain: sensor
  fields:
    amount_in_minor_units:
      required: true
      selector:
        number:
          min: 0
          max: 200000
update: